package com.example.hellotwodbs;

import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class SimpleData {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField
	long millis;
	@DatabaseField
	boolean even;

	SimpleData() {
		// needed by ormlite
	}

	public SimpleData(long millis) {
		this.millis = millis;
		this.even = ((this.millis % 2) == 0);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("millis=").append(millis);
		sb.append(", ").append("even=").append(even);
		return sb.toString();
	}
}
